### PR TITLE
Added README.md with content from VDCT status page on EPICWIKI

### PR DESCRIPTION
**Pull request by tfors-aps**
This PR addresses issue #1.

### CODE REVIEW

**Comment by ralphlange** [comment]
Do the Cosylab links still work?

**Comment by tfors-aps** [comment]
The links appear to work, but the mailing list looks like it's gone and I would guess the bug reporting mailing list no longer works?

If you'd like me to correct any links, I'd be happy to update the PR.

**Comment by msekoranja** [comment]
No. This README.md (EPICSWIKI) is "very much outdated". Not all links work. Bug reporting should be done via GitHub issues now. In fact, I would do a full transition to github (docs + download of the latest).

**Comment by tfors-aps** [comment]
I'm removing the Cosylab links from the README except for the one mentioned in a historical context.  Should I link at all to the EPICSWIKI page and mention that it is outdated? Is there anything of value there?

**Comment by ralphlange** [comment]
Approve.

This is a good start. The Wiki page is more than ten years old - while there might be some things that are still valid, I don't think it is a useful reference.

**Comment by ralphlange** [comment]
NB: You can close the issue from a commit message - see [GitHub Doc](https://help.github.com/articles/closing-issues-via-commit-messages/). Closing happens when the commit is eventually merged in the default branch - safe to use in PRs, even if they should be rejected.

**Pull request merged**
